### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ZeroSkill830** [timbru31/cordova-plugin-lottie-splashscreen#256]
# Bug report
I've installed lottie in my project but when the app is started it crashes.

## What steps will reproduce the problem?
Run the project on Android/IOS

## Expected output
The app starts correctly

## What do you see instead?
The app crashes

## Log file of the issue/error
```
2020-11-10 20:46:16.744 23704-23704/it.viewersapp.influencer W/System.err: java.lang.ClassNotFoundException: de.dustplanet.cordova.lottie.LottieSplashScreen
2020-11-10 20:46:16.746 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.Class.classForName(Native Method)
2020-11-10 20:46:16.746 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.Class.forName(Class.java:454)
2020-11-10 20:46:16.746 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.Class.forName(Class.java:379)
2020-11-10 20:46:16.746 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
2020-11-10 20:46:16.746 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.init(PluginManager.java:86)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at it.viewersapp.influencer.MainActivity.onCreate(MainActivity.java:39)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.Activity.performCreate(Activity.java:7957)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.Activity.performCreate(Activity.java:7946)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8125)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2020-11-10 20:46:16.747 23704-23704/it.viewersapp.influencer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "de.dustplanet.cordova.lottie.LottieSplashScreen" on path: DexPathList[[zip file "/data/app/it.viewersapp.influencer-KC-GDiCkuXeikqeghswcIQ==/base.apk"],nativeLibraryDirectories=[/data/app/it.viewersapp.influencer-KC-GDiCkuXeikqeghswcIQ==/lib/arm64, /system/lib64]]
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer W/System.err: 	... 26 more
2020-11-10 20:46:16.749 23704-23704/it.viewersapp.influencer I/System.out: Error adding plugin de.dustplanet.cordova.lottie.LottieSplashScreen.
2020-11-10 20:46:16.750 23704-23704/it.viewersapp.influencer D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-11-10 20:46:16.751 23704-23704/it.viewersapp.influencer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.viewersapp.influencer, PID: 23704
    java.lang.RuntimeException: Unable to start activity ComponentInfo{it.viewersapp.influencer/it.viewersapp.influencer.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3632)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
        at it.viewersapp.influencer.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7957)
        at android.app.Activity.performCreate(Activity.java:7946)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
```

## Version information
``` 
cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v12.16.1
  npm: 6.13.4

Plugins:
  com-badrit-base64
  cordova-plugin-add-swift-support
  cordova-plugin-androidx
  cordova-plugin-androidx-adapter
  cordova-plugin-appavailability
  cordova-plugin-device
  cordova-plugin-facebook4
  cordova-plugin-geolocation
  cordova-plugin-globalization
  cordova-plugin-inappbrowser
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-lottie-splashscreen
  cordova-plugin-nativegeocoder
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-streaming-media
  cordova-plugin-whitelist

Android platform:
  *************************************************************************
  The "android" command is deprecated.
  For manual SDK, AVD, and project management, please use Android Studio.
  For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
  *************************************************************************
  Running /usr/local/Caskroom/android-sdk/4333796/tools/bin/avdmanager list target

  Available Android targets:==============] 100% Fetch remote repository...       

iOS platform:
  Xcode 12.1
  Build version 12A7403

config.xml <<EOF
<?xml version='1.0' encoding='utf-8'?>
<widget id="it.viewersapp.influencer" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Viewers</name>
    <description>Make money, not friends.</description>
    <author email="hi@ionicframework.com" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="22" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="none" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="LottieAnimationLocation" value="www/assets/media/splash.json" />
    <preference name="LottieFullScreen" value="true" />
    <preference name="LottieLoopAnimation" value="true" />
    <preference name="AndroidXEnabled" value="true" />
    <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
            <string>We use your location for full functionality of certain app features.</string>
        </edit-config>
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <icon height="216" src="resources/ios/icon/icon-108@2x.png" width="216" />
        <splash height="2688" src="resources/ios/splash/Default-2688h~iphone.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-2688h~iphone.png" width="2688" />
        <splash height="1792" src="resources/ios/splash/Default-1792h~iphone.png" width="828" />
        <splash height="828" src="resources/ios/splash/Default-Landscape-1792h~iphone.png" width="1792" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
</widget>

EOF

package.json <<EOF
{
  "name": "ViewersCompany",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "resources": "cordova-res ios && cordova-res android && node scripts/resources.js"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@ionic-native/app-availability": "^5.28.0",
    "@ionic-native/base64": "^5.28.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/facebook": "^5.27.0",
    "@ionic-native/full-screen-image": "^5.28.0",
    "@ionic-native/geolocation": "^5.26.0",
    "@ionic-native/globalization": "^5.22.0",
    "@ionic-native/in-app-browser": "^5.19.1",
    "@ionic-native/lottie-splash-screen": "^5.29.0",
    "@ionic-native/native-geocoder": "^5.26.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/streaming-media": "^5.19.1",
    "@ionic/angular": "^5.0.0-rc.5",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "chartjs-plugin-dragdata": "^1.1.1",
    "com-badrit-base64": "^0.2.0",
    "cordova-android": "^9.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-lottie-splashscreen": "^0.2.21",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-streaming-media": "^2.2.0",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-res": "^0.15.1",
    "core-js": "^2.5.4",
    "google-maps": "^4.2.3",
    "ngx-mask-ionic": "^1.1.2",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "8.1.3",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-streaming-media": {},
      "cordova-plugin-globalization": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-nativegeocoder": {
        "LOCATION_WHEN_IN_USE_DESCRIPTION": "Use geocoder service"
      },
      "cordova-plugin-facebook4": {
        "APP_ID": "545044866223229",
        "APP_NAME": "Viewers Company~",
        "FACEBOOK_HYBRID_APP_EVENTS": "false",
        "FACEBOOK_ANDROID_SDK_VERSION": "5.13.0"
      },
      "cordova-plugin-appavailability": {},
      "com-badrit-base64": {},
      "cordova-plugin-lottie-splashscreen": {},
      "cordova-plugin-androidx-adapter": {},
      "cordova-plugin-androidx": {}
    },
    "platforms": [
      "browser",
      "ios",
      "android"
    ]
  }
}
``` 

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Please read the FAQ and installation instructions: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/blob/master/FAQ.md
