### ISSUE TITLE
App instantly crashes after installation - HELP

### ISSUE THREAD

**Issue by weatherr** [timbru31/cordova-plugin-lottie-splashscreen#259]
Hello,

After adding the cordova-plugin-lottie-splashscreen plugin, when I build the app and install it on my device it just closes/crashes instantly. I am developing it on IONIC and it was building just fine before adding this plugin.

I read forums, stackoverflow and here on github but nothing works and I worked really hard on a splashcreen that I want to use.

I added the necessery, preference name="AndroidXEnabled" value="true", to the config.xml file (although in the console it still says will blue letters:
![image](https://user-images.githubusercontent.com/32965766/99885794-15c9ae00-2c40-11eb-92a4-271566cdcfe3.png)

Also tried adding the "cordova-plugin-androidx-adapter" cause it didn't even let me build without it and now it lets me build but the app crashes instantly. 

Here is a log from when it crashes on my phone (I am using a XIAOMI Redmi Note 8 Pro):
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/io.ionic.starter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3335)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7551)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
 at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
 at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
 at org.apache.cordova.PluginManager.init(PluginManager.java:86)
 at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
 at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
 at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
 at io.ionic.starter.MainActivity.onCreate(MainActivity.java:39)
 at android.app.Activity.performCreate(Activity.java:7893)
 at android.app.Activity.performCreate(Activity.java:7880)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
 ... 11 more

Thanks in advance!

**Comment by timbru31** [comment]
Read the README and the FAQ. Do not delete parts of the issue template.
