### ISSUE TITLE
App crash on Android

### ISSUE THREAD

**Issue by ZeroSkill830** [timbru31/cordova-plugin-lottie-splashscreen#264]
# Bug report
When i open the app it crashes
## What steps will reproduce the problem?
Open the app
## Expected output
The app starts correctly
## What do you see instead?
Nothing, app crashes
## Log file of the issue/error
```
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err: java.lang.ClassNotFoundException: de.dustplanet.cordova.lottie.LottieSplashScreen
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.Class.classForName(Native Method)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.Class.forName(Class.java:454)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.Class.forName(Class.java:379)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
2020-12-07 12:51:04.751 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.PluginManager.init(PluginManager.java:86)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at it.viewersapp.influencer.MainActivity.onCreate(MainActivity.java:39)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.Activity.performCreate(Activity.java:7963)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.Activity.performCreate(Activity.java:7952)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8167)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-07 12:51:04.752 23947-23947/it.viewersapp.influencer W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "de.dustplanet.cordova.lottie.LottieSplashScreen" on path: DexPathList[[zip file "/data/app/it.viewersapp.influencer-D8tyc5Z7hJXDc1juahPIrQ==/base.apk"],nativeLibraryDirectories=[/data/app/it.viewersapp.influencer-D8tyc5Z7hJXDc1juahPIrQ==/lib/arm64, /system/lib64]]
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-12-07 12:51:04.753 23947-23947/it.viewersapp.influencer W/System.err: 
```
## Version information

Ionic:
```
  {
  "name": "ViewersInfluencer",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "resources": "cordova-res ios && cordova-res android && node scripts/resources.js"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@ionic-native/app-availability": "^5.28.0",
    "@ionic-native/base64": "^5.28.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/facebook": "^5.27.0",
    "@ionic-native/full-screen-image": "^5.28.0",
    "@ionic-native/geolocation": "^5.26.0",
    "@ionic-native/globalization": "^5.22.0",
    "@ionic-native/in-app-browser": "^5.19.1",
    "@ionic-native/lottie-splash-screen": "^5.29.0",
    "@ionic-native/native-geocoder": "^5.26.0",
    "@ionic-native/onesignal": "^5.28.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/streaming-media": "^5.19.1",
    "@ionic/angular": "^5.0.0-rc.5",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "chartjs-plugin-dragdata": "^1.1.1",
    "com-badrit-base64": "^0.2.0",
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-lottie-splashscreen": "^0.9.1",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-streaming-media": "^2.2.0",
    "cordova-plugin-whitelist": "1.3.3",
    "cordova-res": "^0.15.1",
    "core-js": "^2.5.4",
    "google-maps": "^4.2.3",
    "ngx-mask-ionic": "^1.1.2",
    "onesignal-cordova-plugin": "^2.11.1",
    "recursive-readdir": "^2.2.2",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.6.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "8.1.3",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-streaming-media": {},
      "cordova-plugin-globalization": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-nativegeocoder": {
        "LOCATION_WHEN_IN_USE_DESCRIPTION": "Use geocoder service"
      },
      "cordova-plugin-facebook4": {
        "APP_ID": "545044866223229",
        "APP_NAME": "Viewers Influencer~",
        "FACEBOOK_HYBRID_APP_EVENTS": "false",
        "FACEBOOK_ANDROID_SDK_VERSION": "5.13.0"
      },
      "cordova-plugin-appavailability": {},
      "com-badrit-base64": {},
      "cordova-plugin-lottie-splashscreen": {},
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {},
      "onesignal-cordova-plugin": {}
    },
    "platforms": [
      "browser",
      "android",
      "ios"
    ]
  }
}
```
## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by ZeroSkill830** [comment]
It was my fault, i was using an unsupported  "cordova-android" version
