### ISSUE TITLE
Installing the Plugin causes Android app to crash

### ISSUE THREAD

**Issue by hoi4** [timbru31/cordova-plugin-lottie-splashscreen#43]
Hi,

I generated a new IonicV3 project using `ionic start myApp tabs --type=ionic-angular`.
After installing the plugin using `cordova plugin add cordova-plugin-lottie-splashscreen` the app does not start anymore and crashes instantly.

I used logcat to get some logs:
```
02-08 08:19:26.951 29741 29741 E AndroidRuntime: FATAL EXCEPTION: main
02-08 08:19:26.951 29741 29741 E AndroidRuntime: Process: io.ionic.starter, PID: 29741
02-08 08:19:26.951 29741 29741 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/io.ionic.starter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread.-wrap12(Unknown Source:0)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:108)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:166)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7529)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
02-08 08:19:26.951 29741 29741 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.PluginManager.init(PluginManager.java:86)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at io.ionic.starter.MainActivity.onCreate(MainActivity.java:39)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7383)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
02-08 08:19:26.951 29741 29741 E AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
```

The same happens when using IonicV4.

I hope you can help me with that.
Thanks in advance!

**Comment by timbru31** [comment]
Hi,

could you please post the output of `npx ionic info`? Besides that, have you installed the plugin to an existing platform? Or first installed the plugin and then added the android platform?

**Comment by hoi4** [comment]
Output of `npx ionic info`:

```
Ionic:

   ionic (Ionic CLI)  : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/Cellar/node@10/10.15.0/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

I have the problem in both cases:
- When first adding the platform and then installing the plugin
- When first installing the plugin and then adding the platform

When not configuring anything in config.xml, the app crashes.
When specifying a location of an animation, the app does not crash.
When specifying another preference besides LottieAnimationLocation the app crashes. (I tried setting LottieBackgroundColor)

Do I have to uninstall the standard splashscreen cordova plugin?

**Comment by timbru31** [comment]
You can install the other splash screen plugin, but both can co-exist. Ideally you replace the “stock” splash screen plugin with this one. Some plugins like `cordova-plugin-ionic` have a dependency on the other splash plugin though. I’m going to add a small section in the README, to explain co-behavior.


Could you possibly share your config.xml?

**Comment by timbru31** [comment]
I believe this issue is caused by the installation flow: `platform add android -> add plugin`. In this case the required hook is not executed.  
I'll update the plugin to execute the hook on plugin add, too.  
The following command should fix the issue: `node plugins/cordova-plugin-lottie-splashscreen/hooks/android/copy_build_extras.js`

**Comment by marckassay** [comment]
I believe I had the same issue as @hoi4 but using Ionic 4 for Android. Executing @timbru31's `copy_build_extras.js` in CLI resolved the issue!

@timbru31 this is an awesome project, clean and well documented too! Thanks!

**Comment by Deusing** [comment]
I cannot get it to work :(

```
ionic start myApp tabs --type=ionic-angular
cd myApp && ionic cordova plugin add cordova-plugin-lottie-splashscreen
ionic cordova platform add android
ionic cordova run android
```

it just crashes.
Output from `npx ionic info` 

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/deusing/Android/Sdk)
   NodeJS            : v10.4.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15
```

**Comment by timbru31** [comment]
Please try installing the beta version.

**Comment by caska22** [comment]
@timbru31 Hello, i am having the same issue but i cant find that file called copy_build_extras.js to execute it? what i am doing wrong? help me please!!

**Comment by timbru31** [comment]
Make double sure you are using cordova-android@9 and set the two flags from the readme, if it still not works open a new issue, follow the issue template please.
